version: '3'
networks:
  default:
    ipam:
      config:
        - subnet: ${TEST_NETWORK}
volumes:
  #mongodbdata: {}
  dbdata: {}

services:
  mongo:
    build: ./mongov4
    image: core5g_mongo:v1
    container_name: mongo
    env_file:
      - .env
    volumes:
      - ./mongov4:/mnt/mongo
      - /opt/mongodb/mongodbdata:/var/lib/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - "27017/udp"
      - "27017/tcp"
    networks:
      default:
        ipv4_address: ${MONGO_IP}